/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=scripts/typegen.env.example --include-runtime=false --env-interface=CloudflareBindings worker/worker-configuration.d.ts` (hash: 2960770ebe7519c232c76e8ad5db629c)
interface __BaseEnv_CloudflareBindings {
	BUCKET: R2Bucket;
	DB: D1Database;
	ANALYTICS: AnalyticsEngineDataset;
	UPLOAD_RATE_LIMITER: RateLimit;
	UPLOAD_PART_RATE_LIMITER: RateLimit;
	RESOLVE_RATE_LIMITER: RateLimit;
	DOWNLOAD_RATE_LIMITER: RateLimit;
	VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	APP_VERSION: "2.6.0";
	R2_BUCKET_NAME: "r2filebox-files";
	D1_DATABASE_NAME: "r2filebox-db";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_VERSION" | "R2_BUCKET_NAME" | "D1_DATABASE_NAME">> {}
}
