/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings worker/worker-configuration.d.ts` (hash: a06d90e122c3b8912262d3c7eb959d58)
interface __BaseEnv_CloudflareBindings {
	BUCKET: R2Bucket;
	DB: D1Database;
	UPLOAD_RATE_LIMITER: RateLimit;
	UPLOAD_PART_RATE_LIMITER: RateLimit;
	RESOLVE_RATE_LIMITER: RateLimit;
	DOWNLOAD_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	APP_NAME: "R2FileBox";
	APP_DESCRIPTION: "Private code-based file sharing on Cloudflare R2";
	APP_VERSION: "1.40";
	R2_BUCKET_NAME: "r2filebox-files";
	D1_DATABASE_NAME: "r2filebox-db";
	CODE_LENGTH: "12";
	MAX_UPLOAD_BYTES: "52428800";
	MAX_TOTAL_STORAGE_BYTES: "8589934592";
	DEFAULT_EXPIRE_HOURS: "24";
	MAX_EXPIRE_HOURS: "168";
	DEFAULT_MAX_DOWNLOADS: "10";
	CLEANUP_BATCH_SIZE: "100";
	ENABLE_TEXT_SHARE: "true";
	ENABLE_FILE_SHARE: "true";
	ENABLE_PUBLIC_UPLOAD: "true";
	ENABLE_AUDIT_LOG: "true";
	ENABLE_ACCESS_LOG: "false";
	ENABLE_NATIVE_RATE_LIMIT: "true";
	RATE_LIMIT_UPLOAD_PER_MINUTE: "10";
	RATE_LIMIT_UPLOAD_PART_PER_MINUTE: "80";
	RATE_LIMIT_RESOLVE_PER_MINUTE: "120";
	RATE_LIMIT_DOWNLOAD_PER_MINUTE: "120";
	RATE_LIMIT_AUTH_PER_15_MIN: "20";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_NAME" | "APP_DESCRIPTION" | "APP_VERSION" | "R2_BUCKET_NAME" | "D1_DATABASE_NAME" | "CODE_LENGTH" | "MAX_UPLOAD_BYTES" | "MAX_TOTAL_STORAGE_BYTES" | "DEFAULT_EXPIRE_HOURS" | "MAX_EXPIRE_HOURS" | "DEFAULT_MAX_DOWNLOADS" | "CLEANUP_BATCH_SIZE" | "ENABLE_TEXT_SHARE" | "ENABLE_FILE_SHARE" | "ENABLE_PUBLIC_UPLOAD" | "ENABLE_AUDIT_LOG" | "ENABLE_ACCESS_LOG" | "ENABLE_NATIVE_RATE_LIMIT" | "RATE_LIMIT_UPLOAD_PER_MINUTE" | "RATE_LIMIT_UPLOAD_PART_PER_MINUTE" | "RATE_LIMIT_RESOLVE_PER_MINUTE" | "RATE_LIMIT_DOWNLOAD_PER_MINUTE" | "RATE_LIMIT_AUTH_PER_15_MIN">> {}
}
